server:
    address: 0.0.0.0
    port: 8082
spring:
  application:
    name: IdentityAndAccessManagement
  # 1. Datasource Configuration (Connection Details)
  datasource:
    url: jdbc:h2:file:./data/my_db_file
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # 2. H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-db-console

  # 3. JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  security:
    user:
      name: qwerty
      password: qwerty
      roles: ADMIN
  logging:
    level:
       org:
        springframework:
            security: DEBUG
